version: "3"
services:
  sharepage: &foo
    image: node
    command:
      - yarn
      - start
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  sharepage_dev:
    <<: *foo
    command:
      - tail
      - -f
      - /dev/null
