version: "3"
services:
  sharepage: &foo
    image: node
    command: >
      /bin/bash -c "yarn && yarn start"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  sharepage_dev:
    <<: *foo
    command: >
      /usr/bin/tail -f /dev/null
