version: "3.4"
x-proto: &proto
  image: node
  command: >
    /bin/bash -c "yarn && yarn start"
  working_dir: /app
  volumes:
    - .:/app
  ports:
    - "3000:3000"

services:
  sharepage:
    <<: *proto
    networks:
      - www_default

  sharepage_dev:
    <<: *proto
    command: >
      /usr/bin/tail -f /dev/null

networks:
  www_default:
    external:
      name: www_default
